version: '3.1'
services:
  db:
    hostname: mysql
    image: mysql:8.0.23
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
  adminer:
    hostname: mysql
    image: adminer
    restart: always
    ports:
      - "8580:8080"


  application:
    image: arabkhan/turbo-az:1.0.5be864b.jar
    restart: always
    ports:
      - "8080:8080"
    environment:
      - DB_CONNECTION_IP=db
      - DB_CONNECTION_USERNAME=root
      - DB_CONNECTION_PASSWORD=password
      - DB_CONNECTION_PORT=3306
    depends_on:
      - db

volumes:
  db_data:

